#!/bin/bash

# This file is part of RobinHood 4
# Copyright (C) 2025 Commissariat a l'energie atomique et aux energies
#                    alternatives
#
# SPDX-License-Identifer: LGPL-3.0-or-later

for program in rbh-sync rbh-find rbh-lfind rbh-fsevents; do
    if ! command -v $program &> /dev/null; then
        echo "This command requires $program to be installed"
        exit 1
    fi
done

function update_directory_expiration_date
{
    local URI="$1"
    local directory_ID="$2"
    local expiration_date="$3"

    rbh-fsevents - "$URI" <<EOF
--- !inode_xattr
"id": !!binary $directory_ID
"xattrs":
  "trusted.expiration_date": !int64 $expiration_date
...
EOF
}

function check_expiration_date
{
    local URI="$1"
    local directory="$2"
    local directory_ID="$3"
    local expires="$4"
    local expiration_date="$5"
    local mount_point="$6"

    local max_time=$(rbh-find "$URI#$directory" \
                        -type f -printf "%A\n%T\n" | sort -rn | head -n 1)

    echo "Directory '$directory' expiration date is set to '$expiration_date'"

    if [ -z "$max_time" ]; then
        echo "Directory '$directory' has expired and it is empty, no other check needed"
        if [ ! -z "$delete_found" ] && [ ! -z "$directory" ]; then
            find "$mount_point/$directory" -depth -exec "rmdir" {} ";"
        fi
        return 0
    fi

    echo "The last accessed file in it was accessed on '$(date -d "@$max_time")'"

    local current="$(date +%s)"

    if (( max_time + expires > current )); then
        local new_expiration_date=$((max_time + expires + 1))

        echo "Expiration of the directory should occur '$expires' seconds after it's last usage"
        echo "Changing the expiration date of '$directory' to '$(date -d "@$new_expiration_date")'"
        update_directory_expiration_date "$URI" "$directory_ID" \
                                         "$new_expiration_date"
        setfattr -n trusted.expiration_date -v "$new_expiration_date" \
                                               "$mount_point/$directory"
    else
        if [ ! -z "$delete_found" ] && [ ! -z "$directory" ]; then
            echo "Directory '$directory' has expired and will be deleted"
            rm -rf "$mount_point/$directory"
        else
            echo "Directory '$directory' has expired"
        fi
    fi
}

function handle_non_relative_expiration()
{
    local directory="$1"
    local expiration_date="$2"
    local expires="$3"
    local mount_point="$4"

    echo "Directory '$directory' expired on '$expiration_date'"

    if [ "$expires" == "None" ]; then
        echo "Expiration attribute is unknown, so we cannot determine if the" \
             "directory is really expired or not. Skipping '$directory'"
        return 0
    fi

    if [ ! -z "$delete_found" ] && [ ! -z "$directory" ]; then
        rm -rf "$mount_point/$directory"
    fi
}

function run_retention_updater
{
    local URI="$1"
    local mount_point="$2"
    local tmp_file="$(mktemp tmp.XXXXXX)"

    if [ ! -z "$conf_file" ]; then
        local config_option="--config $conf_file"
    fi

    rbh-lfind $config_option $URI -type d -expired -printf "%p|%e|%E|%I\n" |
        while IFS='|' read -r dir expires expiration_date ID; do

        if [ "${expires:0:1}" != "+" ]; then
            handle_non_relative_expiration "$dir" "$expiration_date" \
                                           "$expires" "$mount_point"

            echo "true" > $tmp_file

            continue
        fi

        check_expiration_date "$URI" "$dir" "$ID" "$expires" \
                              "$expiration_date" "$mount_point"
        echo "true" > $tmp_file
    done

    local found_something="$(cat $tmp_file)"
    if [ -z "$found_something" ]; then
        echo "No directory has expired"
    fi

    rm $tmp_file
}

function print_doc
{
    echo "Usage: rbh-update-retention URI mount_point [--delete] [--config PATH] [--help]"
    echo ""
    echo "Update the retention of attributes of any directory that is expired,"
    echo "based on their content's last accessed time."
    echo "If a directory is expired, it is printed to the output."
    echo ""
    echo "'--config PATH'   path to a configuration file, used to determine the"
    echo "                  expiration attribute to check for"
    echo "'--delete'        delete the expired directories instead of just printing"
    echo "'--help'          print this message"
    echo ""
}

if [ $# -lt 2 ]; then
    echo "Please specify a URI to update and the mount point of the entries"
    exit 1
fi

while :
do
    if [ -z "$1" ]; then
        break
    fi

    case "$1" in
        --delete)
            if [ "$delete_found" == "true" ]; then
                echo "Delete option already given"
                exit 1
            fi
            delete_found=true
            ;;
        --help)
            print_doc
            exit 0
            ;;
        --config)
            if [ "$config_found" == "true" ]; then
                echo "Config option already given"
                exit 1
            fi

            config_found=true
            conf_file="$2"
            shift
            ;;
        *)
            if [ ! -z "$args_found" ]; then
                echo "URI and mount point already given"
                exit 1
            fi

            URI="$1"
            mount_point="$2"
            args_found=true
            shift
            ;;
    esac

    shift
done

if [ ! -d "$mount_point" ]; then
    echo "Mount point provided is not a directory, please provide one"
    exit 1
fi

run_retention_updater "$URI" "$mount_point"
